<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">
		<div class="col-md-12">
			<form method="post" action="/autenticar">
				<div class="row">
					<div class="col">
						<input type="text" name="email" class="form-control" placeholder="E-mail">
					</div>
					<div class="col">
						<input type="password" name="senha" class="form-control" placeholder="Senha">
					</div>
					<div class="col-auto">
						<button type="submit" class="btn btn-primary mb-2">Entrar</button>
					</div>
				</div>

				<?php if($this->view->login == 'erro') { ?>
					<div class="row">
						<div class="col">
							<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
						</div>
					</div>
				<?php } ?>
			</form>
		</div>
		<div class="col-md-12">
			<div class="col">

				<h2 class="mt-5 subtitle">Aministrador</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>

      </div>
    </div>
  </div>
</div>