<nav class="navbar navbar-expand-sm navbar-collapse bg-success menu">
    <div class="container">
		<h1>Cores</h1>
        <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="/timeline" class="nav-link text-white"><h4>Home</h4></a>
              </li>
			  <li class="nav-item">
			  	<a href="/procura_corAdmin" class="nav-link text-white"><h4>Buscar</h4></a>
              </li>
              <li class="nav-item">
                <a href="/sair" class="nav-link text-white"><h4>Sair</h4></a>
              </li>
            </ul>
        </div>
    </div> 
</nav>
<section id="azul">
          <div class="container ml-auto meio e">
            <div class="row">
              <div class="col-md-12">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                  <ol class="carousel-indicators home">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <h1 class="display-4">Jogos</h1>
                    </div>
                    <div class="carousel-item">
                      <h1 class="display-4">Amigos</h1>
                    </div>
                    <div class="carousel-item">
                      <h1 class="display-4">Comunidade sempre ativa</h1>
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              </div>
             </div>
          </div>
</section>
<section id="home">
<div class="container mt-12 espaco meio">
	
				<form action="/registrarCores" method="post">
						<div class="form-group">
							<input type="text" name="Cor" class="form-control" placeholder="Cor">
						</div>
						
						<div class="form-group">
							<input type="text" name="Detalhes" class="form-control" placeholder="Detalhes">
						</div>
						<button type="submit" class="btn btn-primary btn-block">Cadastrar cor</button>

						
				</form>
				
</div>
</section>